### ISSUE TITLE
Support for plans, explorative and theoretical research

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/wikidata-identifiers#3]
```
{
  "Q131841": "Idea",
  "Q1371819": "Plan",
  "Q17737": "Theory",
  "Q2412849": "Literature review",
  "Q321703": "Premise",
  "Q41719": "Hypothesis",
  "Q748250": "Prediction",
  "Q94535766": "Claim",
  "Q185698": "Methodology",
  "Q82604": "Design",
  "Q41689629": "Procedure",
  "Q16798631": "Equipment",
  "Q42848": "Data",
  "Q1070421": "Script",
  "Q1347572": "Evidence",
  "Q217602": "Analysis",
  "Q17104930": "Outcome",
  "Q3030248": "Discussion",
  "Q333291": "Abstract",
  "Q1318295": "Narrative",
  "Q604733": "Presentation",
  "Q265158": "Review",
  "Q55107540": "Other"
}
```

Submitting as issue as I don't have write access. @chartgerink could you sort that out or create a PR?

For Hypergraph this would currently imply that we'd need to reduce the (font) size of the content type dropdown list to make this usable. I do have reason to believe that all these would be valuable, especially to non-empirical researchers, and would likely also inspire users to publish more than just what would traditionally go into a paper.

**Comment by juliangruber** [comment]
> Submitting as issue as I don't have write access.

You could also create a PR

**Comment by jameslibscie** [comment]
@juliangruber I didn't have rights for creating PRs yesterday without forking

**Comment by juliangruber** [comment]
What's the difference :P Let's work on the permissions with Chris

**Comment by chartgerink** [comment]
@juliangruber forgot to add the @hypergraph-xyz/contributor team to have write access. Fixed it at the organisation level that people by default have write access.
